### ISSUE TITLE
[Question] JSON to HTML

### ISSUE THREAD

**Issue by forever84721** [formio/formio#1008]
Is there a way to directly export the JSON completed by the builder into HTML text? Or in FormIO.js?
Thank you.

**Comment by travist** [comment]
Not currently. The way our form platform works is as a "client rendered" form platform instead of server rendered. There will eventually be a way to do it as we start to bring in the Core renderer @ https://github.com/formio/formio.js into the server code (which we are starting to do for validations), but we are still a ways from this.

**Comment by forever84721** [comment]
I got it.
Thank you.
