### ISSUE TITLE
[BUG] v2.0.0-beta.8 breaks authentication

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#1015]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: v2.0.0-beta.8
- Formio.js version: `any`
- Frontend framework: `any`
- Browser: `any`
- Browser version: `any`

## Steps to Reproduce
1. Checkout latest version `v2.0.0-beta.8`
2. Run local server and point browser to http://localhost:3001
3. Try to login using admin credentials

## Expected behavior

User can login without problems

## Observed behavior

An authentication error is triggered

**Comment by airarrazaval** [comment]
@randallknutson FYI. Still haven't checked what is causing the problem, but had to revert to `v2.0.0-beta.7`.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
