### ISSUE TITLE
reCaptcha component  does not appear anywhere

### ISSUE THREAD

**Issue by jaimestuardo** [formio/formio#1027]
First of all, I am connecting to https://next.form.io/ and when I press "Login with GItHub" button, a new popup is opened with me logged in. It seems that popup is a normal popup windows in the browser because I cannot drag and drop in the tabs window of the browser (Chrome), so that I canno only maximize it, but not join it together with the other tabs in the browser.

Well... the problem could be stated simply. I have set reCaptcha keys for my form, but I cannot find any way to actually add it to the form. It does not appear in the form editor (in the same page where I can add form fields).

Any help?

Thanks
Jaime

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
