### ISSUE TITLE
[BUG] error 502 :  Bad Gateway and 503 :  Service Temporarily Unavailable when too many requests

### ISSUE THREAD

**Issue by gismomtl** [formio/formio#1042]
## Environment

formio 2.0.0-rc.3 

- Hosting type
  - [] Form.io
  - [x] Local deployment - Docker
 
Hi, 
if we try to load in batch data through the POST submission
After a few successful submission, we receive 502 and 503 error as we create to much requests...

Is there any way to avoid such behavior and have a way to perform batch creation without having to set 1 or 2 seconds delay between each submission.. with 40000 entries to be created.. it's not a way we want to use formio... 11h to wait until completion..

**Comment by randallknutson** [comment]
The server should be able to handle this so we need to add this to our list to check before we release 2.0.0. If you have any insight into why it is happening, please let us know.

**Comment by randallknutson** [comment]
We don't have an officially supported version of formio in a docker container. We have our enterprise server that is in docker. Furthermore, nginx in front of docker is far out of our scope. While we can help with the setup of a proxy with nginx (we have some help docs around setting this up), troubleshooting nginx configurations is not something we are experts at.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
