### ISSUE TITLE
await is not working

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio#1051]
I used below syntax. 
let response = await fetch('url');

But is shows error,

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
