### ISSUE TITLE
Unauthorized error while accessing a standalone form in form.io trail version

### ISSUE THREAD

**Issue by vmedimpu** [formio/formio#1061]
I am trying to access a standalone form designed in trail version, but when I access the form i keep getting unauthorized error.
Where as I can still access and submit my old forms I created 10 days ago.

I tried to create a new account just to make sure if the issue is related trail version expiry , still on new version I am getting same unauthorized error.

Could you help me what could be the issue here.

**Comment by wag110894** [comment]
@vmedimpu Can you confirm that you have set up your Submission Data Permissions correctly. More information on our roles and permissions can be found here: https://help.form.io/userguide/roles-and-permissions/

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
