### ISSUE TITLE
[QUESTION] Populating a field with a previous submission value based on date

### ISSUE THREAD

**Issue by tmman2** [formio/formio#1062]
Hello!

I am looking to populate a field "startingValue" with the value of the previous submission's "endingValue".  The endingValue that is used should be based off of the user provided "dateOfService" - 1 day.  So, in a new form if a user selects 2020-08-13 as their dateOfService that means we would want to grab the value that was used in a previous submission where dateOfService was equal to 2020-08-12.

Can anyone point me towards some documentation or otherwise?  Have been searching but have not found a good example of something like this.

Thanks!

**Comment by randallknutson** [comment]
You can search submissions to get the most recent submission and then see what the date is from that. For example, you can do a GET https://myproject.form.io/myform/submission?sort=-created&limit=1 which will return the most recent submission. Then you can find your field with the value in it.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
