### ISSUE TITLE
How to use HIDDEN component which is under Data tab. 

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio#1070]
Hi Nitesh here,

What is the purpose and how to use HIDDEN component. 
As name suggested, We can do computation in background without knowing to end user.. but I am not able to drag any component in it.

**Comment by NiteshNagar** [comment]
@wag110894  Hi thanks for the quick response. Can you provide me an example / Screenshot where hidden components is being used.  I am not getting idea from userguide ( http://help.test-form.io/userguide/form-components/#hidden) which you shared for hidden component. 
I tried to provide value in hidden component by using java script but it won't work for me..

**Comment by randallknutson** [comment]
You can use the calculated value field to set the value. If you set the value directly in the html it will not pick up the value correctly.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
