### ISSUE TITLE
Heroku Deploy Button to Try Formio

### ISSUE THREAD

**Issue by ashwinbalaji0811** [formio/formio#1087]
Could you provide us with a **Deploy to Heroku** button, so that we can test it before installing in our production servers?

**Comment by rcermeno** [comment]
For now, you can dockerize it and deploy it manually in a heroku dyno, this has worked perfectly for me.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
