### ISSUE TITLE
Database For two or more Projects

### ISSUE THREAD

**Issue by UmarP19** [formio/formio#1091]
If we create 2 or more projects with different forms,  we worried if  the data that input in each form will be mix in one database. 
is there a way for each data from different form not mix in one data base ?

(Currently our company already purchase enterprise option)

**Comment by randallknutson** [comment]
Our next server version (8.x) will contain per project databases so each project is broken out into separate databases. Unfortunately in the 7.x and below they are all going to be mixed into the same database. They are logically separated since each document has the project id but technically they exist in the same database.

**Comment by UmarP19** [comment]
Thank you for your reply, one more question, if the database logically separated  with project id and we use inquiry function it will not show other data in each for ,  is it correct ?

**Comment by randallknutson** [comment]
Correct. The apis will never return data from a different project in both the current version and the next version. We do a hard filter by project id with all queries.

**Comment by UmarP19** [comment]
Thank you for your reply
