### ISSUE TITLE
[FEATURE REQ] Enhance email action to set reply-to email field

### ISSUE THREAD

**Issue by duttonw** [formio/formio#1098]
Given I am sending an email
When the from address is no-reply@server
Then I want to be able to set reply-to email field header to allow quick response from received emails.

The reason for this is to keep within SPF policies. You can't masquerade as another email address in a contact form.
i.e. say a person contacted you and their email address was xyz@gmail.com
you cannot set the form address to xyz@gmail.com as google and anyone else will drop that email and mark the sending server as a spam open relay.

As such we need the ability to set a reply-to for the persons email address. This allows the received email to be quickly reply-to'ed without human error in copying the email address to the to/reply field.

see https://contactform7.com/best-practice-to-set-up-mail which has good tips in not looking like spam etc.

**Comment by wag110894** [comment]
Hello @duttonw, 

Thank you for reaching out to us with your feature request. We estimate it would take about 4 hours to add this enhancement. Please let us know if you are interested by contacting support@form.io. For reference, the ticket number is FOR-2765.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
