### ISSUE TITLE
Auto Resize for Upload Picture

### ISSUE THREAD

**Issue by UmarP19** [formio/formio#1103]
Hi,

Is  there a function in form.io for automatically resize a picture after we use an upload feature  ? 

thank you

**Comment by randallknutson** [comment]
Images and files are uploaded to third party blob storage like S3 or Azure Blob Storage. Once it is there we don't have any ability to manipulate the file. You can look into this functionality from within the blob storage you choose to modify the file however you'd like.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
