### ISSUE TITLE
Is the multiple language supported for its formio  label?

### ISSUE THREAD

**Issue by joshua60** [formio/formio#1109]
I could not find the multiple language label when editing the form on the demo system. 
If someone could tell the following info, that will be thankful.
- Is there any internationalization and localization features be planed implementing in the near future?
- any functional spec. is initialized ?

**Comment by randallknutson** [comment]
We use the i18n module to translate all strings within forms. While there is no UI for doing this in the form.io portal yet, you can easily do this when embedding forms. You can see an example here: http://formio.github.io/formio.js/app/examples/language.html

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
