### ISSUE TITLE
MongoDB password leak risk

### ISSUE THREAD

**Issue by geekeren** [formio/formio#1112]
Is there any other option to set the mongo DB password instead of inserting it in dbUrl like:
```
mongodb://user:xxx@example.com/db_name
```
the password will be leaked when logging the dbUrl

https://github.com/formio/formio/blob/509d9e80675633131b234ff8bf316b97e35255a8/src/db/index.js#L226

**Comment by airarrazaval** [comment]
Strictly speaking, you are right that it is something to avoid.  Now you must also consider that it is a debug print which will only be visible inside the machine the server is running and shouldn't show in production. Anyone with direct access to the host machine will have access to view all of your formio server configuration and at this point, the debug will be the least of your concerns.

Now, the formio server uses [debug](https://www.npmjs.com/package/debug) which can be configured through the environment variable `DEBUG` to control the level of debugging. 

https://github.com/formio/formio/blob/a7ce3ef5923fa7c0c258e99aa03fdd6efe131ef3/Dockerfile#L45-L48

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
