### ISSUE TITLE
[Question] Form.io benchmarks

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#1124]
Hi, I was wondering if there is any available benchmark for local deployment of Form.io.  Mainly the following:

1. API limits (get - post - put - delete requests per second)
2. Submissions limits (total submissions and max size per submission)

I am really interested in the submissions' limit because of the nature of form.io submissions.  When deleting a submission the the mongodb document is marked as deleted, but is not deleted per se.  So if I am managing thousands of submissions, even if I delete some I will never truly delete it and database size will keep on growing. Is there a solution for this (aside from periodically scan database and manually delete records)?

If there is any other benchmark I would truly appreciate it.

Thanks

**Comment by travist** [comment]
1.) API Limits are mainly dependent on the deployment size of the database. You will also be able to find better metrics for this looking at the database get, put, post, delete metrics since the Form.io server is pretty close to the metal in terms of execution of queries.

2.) Same answer as above. The Form.io server does not implement its own restrictions other than what MongoDB implements.

As for deleting submissions, you will need to implement your own CRON mechanism to perform cleanup of old deleted items on your own timeline (maybe a month after deletion clear it out).

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
