### ISSUE TITLE
[QUESTION] Custom Component Minimal EditForm

### ISSUE THREAD

**Issue by lazatin1323** [formio/formio#1125]
Hi,

I'm trying to create a custom component. I was trying to populate a Select dropdown on minimalEditForm via API. The APi is returning the desired response but the options is not being populated. I'm not sure if there's something wrong with the code but i want to ask if it's even possible in the first place.

![image](https://user-images.githubusercontent.com/73876590/97961968-ab0a1d00-1dcd-11eb-9492-a707f7d20f1a.png)

Thanks

**Comment by travist** [comment]
The ```minimalEditForm``` should be a function that returns the JSON of the form like so...

```
const minimalEditForm = function() {
  return {
    components: [
      { key: 'label', label: 'Label', type: 'textfield'}
    ]
  };
};
```

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
