### ISSUE TITLE
[Question] Is there a form.io renderer for react native or any mobile?

### ISSUE THREAD

**Issue by ullas1989** [formio/formio#1133]
Is there a form.io renderer that we can use with react native or any other mobile device?

I have angular app that is using form-io angular package. I am looking into ways how I can add same renderer functionality for mobile.

**Comment by wag110894** [comment]
Hello @ullas1989,

Here you go: https://github.com/formio/react-native-formio

**Comment by ullas1989** [comment]
Hi @wag110894. This is pre alpha release and I don't think anyone has worked on it since 2 years.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
