### ISSUE TITLE
How to return data in array format

### ISSUE THREAD

**Issue by nexawo** [formio/formio#1134]
Hello, 
 
I am using formio and I want to return data in array format like it does in editGrid case. I have created a panel and inside panel I have multiple select boxes but when i submit data it send data in object format. Is ther any way so I can submit that data in array. I don't want to use editGrid

**Comment by travist** [comment]
If you wish to have an array of objects, you must either use Edit Grid or Data Grid. If you just need an array of Strings, you can always use the Multiple flag set on TextField components.

**Comment by nexawo** [comment]
I cannot use Edit Grid and multiple Select in my case yeah Datagrid is a option but there is only one problem i.e I want to add Multiple Columne but it add columns from left to write as you can see in fig below 
![image](https://user-images.githubusercontent.com/55268813/98930847-08554b00-24ff-11eb-9933-8a0c62106941.png)

Can I add these column from top to bottom format 

> If you wish to have an array of objects, you must either use Edit Grid or Data Grid. If you just need an array of Strings, you can always use the Multiple flag set on TextField components.

**Comment by travist** [comment]
Make it only have a single column for Data Grid, and then in the "columns" component added to that single column, you will configure it to have more than 2 columns (in this case 4). Why does that not work?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
