### ISSUE TITLE
How to show data in selectbox

### ISSUE THREAD

**Issue by nexawo** [formio/formio#1139]
I am using formio select box and in api key I am returning an object data instead of single value so when I get a data it return the object data and I see [object Object] in my select box. Is there a way so I return the object data but in select box it set the key from the object data. You can see the below img as an example 

![image](https://user-images.githubusercontent.com/55268813/99252341-9cd9e900-2830-11eb-9357-1d07411d486e.png)

**Comment by wag110894** [comment]
Hello @nexawo can you please provide a JSfiddlfe or a form embed URL so we can investigate. Could you also provide what versions you are running?

**Comment by nexawo** [comment]
> Hello @nexawo can you please provide a JSfiddlfe or a form embed URL so we can investigate. Could you also provide what versions you are running?

https://jsfiddle.net/1gs2zxae/
In this fiddle I am passing values in object and get the values in same format but it shows [object Object] instead of text

**Comment by wag110894** [comment]
Hello @nexawo, I am not seeing this issue on the JSfiddle that you provided. Can you provide a video of the issue taking place in the jsfiddle?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
