### ISSUE TITLE
[Question] Difference between "Edit grid" and "Data grid"

### ISSUE THREAD

**Issue by qomhmd** [formio/formio#1145]
It is not clear to me based on [the documentation](https://help.form.io/userguide/data-components/). Is it not better to provide a comparison table for these two (I think) similar components?

**Comment by qodrinzo** [comment]
https://formio.github.io/formio.js/app/examples/editgrid.html

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
