### ISSUE TITLE
Prefilling datagrid on the opensource Formio

### ISSUE THREAD

**Issue by qomhmd** [formio/formio#1147]
Hi. Is there any way to do pre-filling data grid for some rows on the platform? The links below are related to formio.js.

http://formio.github.io/formio.js/app/examples/datagrid.html
https://github.com/formio/formio.js/issues/141

**Comment by antonioluzzi** [comment]
Hi, I m new to form.io.
I'm using form builder, but I don't find the way how to prefill the Datagrid component with remote Rest Service.
Can someone help me?
Regards
Antonio

**Comment by edwinanciani** [comment]
Can you add more information on what is the issue that you are experiencing? To add data in a Data Grid Component you just need to set a Default Value or Calculate Value in the component (Array). Also you can do it in the Submission JSON adding data to the data grid property for example:
DataGrid Property name is myList.
```
submission = {
  data: {
    myList: [{taskName: 'First Task', completed: false}, {taskName: 'Second Task', completed: true}]
  }
}
```

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
