### ISSUE TITLE
"Calculated value" if a condition meet

### ISSUE THREAD

**Issue by qomhmd** [formio/formio#1148]
Hello. I want to calculate values of the disabled inputs (eg, _spec_calc_) if and only if their editable twins (eg, _spec_) are empty. Such a value is calculated using the values of the other filled inputs (eg, _sens_ and _nLR_).

But the values are not calculated until the related twin once becomes filled and then cleared; maybe the required additional event listeners are not created automatically. Anyway, the form's JSON provided [here](https://github.com/formio/formio/files/5579209/statistic.formio.json.txt).

**Comment by wag110894** [comment]
Hello @qodrinzo,

We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period. We will assign one of our senior developers to work directly with you in online sessions. Please let me know if you are interested and I can provide you our Support Package Options.

**Comment by qodrinzo** [comment]
Sorry to inconvenience @wag110894. Interested in that, thanks.

**Comment by wag110894** [comment]
Contact support@form.io and we will send it over to you via email.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
