### ISSUE TITLE
Ability to tailor Webhook JSON sent to Webhook URL?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#117]
Any upcoming ability to undocumented abilities to tailor the JSON that is generated by Webook action?
Would be great if we could tailor the json structure to match what the Webhook URL/system is looking for.

If not the web hook action, then a new action that allows someone to call a Web Service with specific JSON formatting?

Thanks!

**Comment by zackurben** [comment]
Hey @StephenOTT,

This can currently be achieved with our Remote Middleware feature, but not with pure Webhooks. https://help.form.io/developer/info/#middleware

It is currently in our roadmap to add custom formatting to the webhook action, but I can't give you an accurate timeline for that functionality. Since the webhook action is available in this repo, you could make a PR with that additional functionality or email support to possibly expedited the feature.

Let me know if you have any additional questions.
