### ISSUE TITLE
Content-Range: header should conform to RFC7233, Section 4.2

### ISSUE THREAD

**Issue by franke-mc** [formio/formio#1220]
https://example.form.io/company/submission
replies with the following header, among others:
```
Content-Range: 0-9/25
```
This appears to violate https://tools.ietf.org/html/rfc7233#section-4.2 
Probably, instead it should be:
```
Content-Range: items 0-9/25
```
(For more background, see https://savannah.gnu.org/bugs/?60106#comment5 .)

**Comment by travist** [comment]
Thanks for the report. We will take a look.

**Comment by wag110894** [comment]
For reference, the ticket is FIO-2552.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
