### ISSUE TITLE
[Question] How to display the form fields of an particular form based on the role login, finally where admin need to access all the fields?

### ISSUE THREAD

**Issue by chetlrohith97** [formio/formio#1227]
## Environment
Here we got in a requirement where we want to display form fields of an particular form based on the role while login

1)using the user/register page we have created 3 different users
2) Using admin we have created form as TestRole  with 20 fields,
3) Now trying to login with one of the created user as user1 and now trying to access the form, now we are trying to display a few fields of the form like 10 fields
4)while for the 2nd user need to display 15 fields, where 3rd user with the 20 fields.
5)Finally all the fields need to be displayed to the admin 

How can we achieve this scenario with the help of condition tab for the each individual field in the editform section?
i have tried of it using this condition below  
this is condition is been taken form data base of submissions.data.email
{"===" : [ { 'data.email':"user1@gmail.com" }]}   
or 
{
  "===": [
    {
      "submissions.data.email": "user1@gmail.com"
    },
    false
  ]
}
trying to capture value of mailid while the time of login....

Is this correct way to do or required help on this thanks in advance....

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
