### ISSUE TITLE
[BUG] issue with @formio/react

### ISSUE THREAD

**Issue by BKenny11** [formio/formio#1247]
## Steps to Reproduce
1. Installed npm packages
2. Include either Form or FormBuilder in project
3. get an error on building 

Failed to Compile:
./node_modules/@formio/react/lib/components/ReactComponent.js
Module not found: Can't resolve '@formio/core/lib/components/_classes/field/Field'

**Comment by AlexeyDavyd** [comment]
@BKenny11 Could you please specify versions used.
And attach code snippet that causing failure.

**Comment by anoop-pm** [comment]
ReactDOM.render(
  <FormBuilder form={{display: 'form'}} onChange={(schema) => console.log(schema)} />
  , document.getElementById('builder')
);

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
