### ISSUE TITLE
Permissions for Restricting Viewing of Form?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#125]
Is it currently possible to restrict the viewing of a Form?
This would be a restriction that does not allow a form to be loaded without auth.  There does not seem to be any permissions for setting who can load a form (anonymous vs auth/roles).

The scenario would be that some forms may have sensitive labels, content etc, and should only be viewed by auth users who have access to that specific form.

In the current iteration it seems you can restrict the submission to the role, but not the viewing of a form/loading of a form.  This correct?

thanks!

**Comment by zackurben** [comment]
@StephenOTT this is currently available, but undocumented; mainly because we don't have a ui for it yet, this is however on our roadmap.

Exactly how each form has the `submissionAccess` property, there also exists an `access` property. It is formatted, and behaves identical to the `submissionAccess` system, but controls the access of the form itself rather than submissions to the form. By default, each role (the default 3, and any new roles created, before or after any form) has access to read the definition of every form. This is just the default we choose because it seems to fit most of our customers use cases.

So.. if you wanted to ensure that only users with the `Administrator` role could access a form, the permissions on the form would look something like this:

```
{
    submissionAccess: [ ... ], // what ever
    access: [
        {type: 'read_all', roles: [<Your Administrator Role _id>]}
    ]
}
```

If you have a specific question, don't hesitate to ask.

For more information on the permissions system, you can find the permissions documented here: https://help.form.io/userguide/#permissions
