### ISSUE TITLE
[QUESTION] How to Call OAuth-authenticated Webhook?

### ISSUE THREAD

**Issue by jwarrenbc** [formio/formio#1253]
## Environment
- Hosting type: Form.io
- Frontend framework: Standalone form

## Situation
I would like my anonymous form to POST to a REST endpoint on submit. However, the endpoint (Camunda Cloud) is only accessible using OAuth 2. Is there any way to configure form.io to get an OAuth token and pass it along with the POST call? (For clarity: it is the form.io instance that needs to be authenticated, not the user submitting the form.)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
