### ISSUE TITLE
Modify color of default components

### ISSUE THREAD

**Issue by avibu** [formio/formio#1259]
Hello,

Couldn't find anything about that, are we able to modify the color of 'Drag and Drop' box, and the color of the basic components, via the options parameter?

![image](https://user-images.githubusercontent.com/22260300/120185994-9125a100-c21b-11eb-9b0b-37de9cffdca2.png)

**Comment by avibu** [comment]
Hey, 
Trying again, is there a way to modify the color?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
