### ISSUE TITLE
[BUG] Form.io container has mailgun error message and couldn't run

### ISSUE THREAD

**Issue by yhrchan** [formio/formio#1264]
## Environment
Please provide as many details as you can:

- Hosting type
  - [  ] Form.io
  - [x] Local deployment
    - Version: latest from repo
- Formio.js version:
- Frontend framework:
- Browser: Edge
- Browser version:

## Steps to Reproduce
1. Git clone repo
2. npm install
3. docker-compose up -d

## Expected behavior

That Form.io will run and could be accessed through the web browser

## Observed behavior

![2021-06-07 (1)](https://user-images.githubusercontent.com/3683552/121080383-9729fd80-c798-11eb-90f8-bef0d9c3401a.png)

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
