### ISSUE TITLE
On click of a radio button , a checkbox and a textbox should be displayed

### ISSUE THREAD

**Issue by sonam80** [formio/formio#1271]
On click of a radio button in Form.io form , a checkbox and a textbox should be displayed.

**Comment by wag110894** [comment]
Can you provide the form embed or a sandbox of the issue?

**Comment by sonam80** [comment]
I dont know if it is a issue or what but I want to develop this functionality for my form, but I cannot see any option for that. Any help will be appreciated. Thank you.

**Comment by wag110894** [comment]
Do you have a conditional logic set up for the component?

**Comment by sonam80** [comment]
yes and I am able to now display the checkbox and textbox. Thank you for that.
I want to add a upload feature now to the form using custom URL. Can you help me with that?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
