### ISSUE TITLE
[BUG]  Edit JSON, Description and Tooltip fields have issues when edited

### ISSUE THREAD

**Issue by AgileFlex** [formio/formio#1272]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.12.1
- Frontend framework: react 17.0.1
- Browser: Chrome
- Browser version: 91.0.4472.101

## Steps to Reproduce
1. Edit JSON, Description and Tooltip fields have issues when edited
2. Click Edit JSON (any field)
3. Write text in “Component JSON”
4. Result: Text written is displaced from where cursor was located
5. Expected Result: Text entered should follow the cursor location.

## Expected behavior
Text entered should follow the cursor location.

## Observed behavior
Text written is displaced from where cursor was located
![img-01](https://user-images.githubusercontent.com/16820840/122179868-911ad780-ce90-11eb-9beb-07f7b055c7ab.jpg)
![img-02](https://user-images.githubusercontent.com/16820840/122179870-91b36e00-ce90-11eb-97c7-aa6d6d901257.png)

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Hello @AgileFlexAgency,

I am unable to replicate as this working correctly on our Portal. Can you provide a video of the issue?

Thank you.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
