### ISSUE TITLE
QUESTION: Variables in Form Definitions

### ISSUE THREAD

**Issue by ddurham2** [formio/formio#1276]
I have some forms with File elements and I'd like for their storage URL to be based on either a passed in value, some sort of variable, or perhaps on a global 'configuration' submission's value. 

I'm hosting formio myself and with dev, test and production environments, I have to reconfigured all the forms' URLs in each one.

Something like MyForm -> File1 -> Upload Url == StorageURL}/files
... where StorageURL is supplied at runtime.

Is this possible?

Thanks in advance!

**Comment by NoeliaEspada** [comment]
I encountered the same problem as @ddurham2 , did someone find a solution?

**Comment by devsda** [comment]
Still seeking a solution on this.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
