### ISSUE TITLE
Help: How to add custom CSS class in form.io

### ISSUE THREAD

**Issue by vaibhavdwivedi77** [formio/formio#1291]

**Comment by jensonjohn001** [comment]
+1

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
