### ISSUE TITLE
Question: How can i populate data on fields base on calling an api in the drop down.

### ISSUE THREAD

**Issue by abhishekbeesony** [formio/formio#1294]
Example in the drop down i have select id as then other fields in the form should be automatically filled. 

How can i achieved this. Please give me the steps. 
Thank you.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
