### ISSUE TITLE
QUESTION: Is there a way to auto add row depending on the input value?

### ISSUE THREAD

**Issue by massquote** [formio/formio#1307]
I have a number input where user can type the number of rows to be populated in the dataGrid. So if the user type 3 it should create 3 rows in the datagrid. Is there a way to achieve this?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
