### ISSUE TITLE
Override the default value of the enableTime flag on the datetime component

### ISSUE THREAD

**Issue by andreinitescu** [formio/formio#1309]
I'm trying to change the default value of the "Enable Time Input" check-box (in the "Time" tab of the datetime component) to false.

From https://github.com/formio/formio/issues/1032 based on @travist 's answer:
```
const dateTimeSchema = Formio.Components.components.datetime.schema();
dateTimeSchema.enableTime = false;

Formio.Components.components.datetime.schema = function () { return dateTimeSchema; };
```

This sets **all** the existing datetime component in an existing schema to have enableTime false. Not what I wanted.

I also tried @travist 's answer from https://github.com/formio/angular/issues/241#issuecomment-679188332

```
    var editForm = Formio.Components.components.datetime.editForm();
    var enableTime = Formio.Utils.getComponent(editForm.components, 'enableTime');
    enableTime.defaultValue = false;
    Formio.Components.components.datetime.editForm = function () { return editForm; };
```

This doesn't work either.

I tried calling each both before and after calling `await Formio.builder(...)` because that's another thing which is not clear to me, not sure if it even matters.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
