### ISSUE TITLE
How to set a unique key for a element that doesn't change when label changed?

### ISSUE THREAD

**Issue by nilesh-infobeans** [formio/formio#1310]
While creating any new text field or any form element and change the label of that element then the key got changed as per the label, is there any way to make the key unique so if we will change the label it should not change the key of that element. Please suggest.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
