### ISSUE TITLE
[BUG] Error Validations not displaying on page load for fields nested inside another element

### ISSUE THREAD

**Issue by sachinkm7** [formio/formio#1313]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: 4.12.0
- Frontend framework: Angular 11
- Browser: Google Chrome
- Browser version: 92.0.x

## Steps to Reproduce
1. Create a form with any data component say container/data grid or any custom layout such as Accordion.
2. Add some input fields with validations such as required, min length, max length etc within the container, data grid or accordion created.
3. If the input fields has pre-filled invalid data that doesn't satisfy the validation conditions, then the validations and validation message wont display on the input field unless the input field becomes dirty.

## Expected behavior
Expected the validations needs to be displayed on the input fields which has some validation criteria set regardless of whether those input fields are nested inside other elements.

## Observed behavior
If the input fields nested inside a container/data grid/accordion has pre-filled invalid data, then the validations wont display on those input fields on initial page load.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
