### ISSUE TITLE
[Question] Component Save button event

### ISSUE THREAD

**Issue by magaz-serhii** [formio/formio#1317]
Hi, I need to perform some custom javascript logic when user clicks Save button on component edit form. Please tell me, how can I achieve this?
Thanks
![image](https://user-images.githubusercontent.com/1797793/131819393-b4435132-628a-4fa0-8146-d918fafa2378.png)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
