### ISSUE TITLE
[BUG] Email action errored but marked as successful

### ISSUE THREAD

**Issue by mrcandu** [formio/formio#1321]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: Enterprise 7.1.7
- Formio.js version: 4.13.5
- Frontend framework: Vanilla JS
- Browser: Chrome, Edge etc
- Browser version: Latest

## Observed behavior
The email action fails, (in this case due to an SSL handshake error with mailtrap.io), but is marked as successful in the action logs.
Running formio in debug mode, I can see the line `formio:error Error: 139675995327304:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331`
The email is never sent due to the SSL error.

## Expected behavior
The email action to have resulted in `"state": "error"`

## Steps to Reproduce
What caused the error in this case:
1. Configure a stage smtp settings to use mailtrap.io running on port 465 or 587.
2. Create a form with an email action and create a submission.
FYI - Mailtrap does seem to work fine on port 25 though. I've seen issues with Mailtrap with other services.

**Comment by HariVamsiK** [comment]
Hi
I would like to contribute on this issue

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
