### ISSUE TITLE
[BUG] Issue in text fields used within the Data Grid 

### ISSUE THREAD

**Issue by mananu** [formio/formio#1329]
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: Latest 
- Formio.js version: Latest
- Frontend framework: N/A
- Browser: Chrome
- Browser version: 93.0.4577.82

## Steps to Reproduce
1. Please refer to this; https://jsfiddle.net/mangun/dyba65Lq/2/
2. When loaded initially user edits the first text field (can edit the first field but the 2nd and the 3rd gets reset to the calculated value)
3. When the form loads initially, User edits the 2nd or 3rd text fields
4. It is observed that the text field value is reset to the calculated value (i.e. - abc)

## Expected behavior
The user should be able to edit the **2nd and 3rd** text fields within the datagrid without the value getting reset to the calculated value. (Happens only when editing for the first time)
## Observed behavior
The second and the third text fields are reset back to the calculated value, but no change in the first text field
## Example
[JSFiddle](https://jsfiddle.net/mangun/dyba65Lq/2/)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
