### ISSUE TITLE
[BUG] Decimal place still shown when zero decimal places nominated

### ISSUE THREAD

**Issue by KAVA-Leigh** [formio/formio#1330]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment (open source)
    - Version: 
- Formio.js version: latest (v4.13.7-rc.2)
- Frontend framework: none (vanilla JS)
- Browser: any (tested on Chromium, Safari & Firefox)
- Browser version: various

## Steps to Reproduce
1.  Create a Currency field
2. Set the decimal places to 0
3. Uncheck the decimal required checkbox

## Expected behavior
Decimal place not shown in input field

## Observed behavior
decimal place is still shown in the input field i.e. '$1,000,000.' - 
The requirement is to show property values with formatting in fields, but without decimal shown.

**Comment by anujxx** [comment]
@KAVA-Leigh  my concern is also same but i am unable to disable "." after 123 value

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
