### ISSUE TITLE
{BUG} Not getting Tabs  option in layout component

### ISSUE THREAD

**Issue by Ypsolution** [formio/formio#1331]
I have cloned the formio source code and trying to run it on my server but I am not getting Tabs options in my layout components.
I have tried a lot of things but nothing seems to work.

![image](https://user-images.githubusercontent.com/63725690/135071917-6987a0aa-7e03-406f-b0d3-bbefa3a65c72.png)

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
