### ISSUE TITLE
Signature component is not working on pdf while in device (touch events)

### ISSUE THREAD

**Issue by CrackerakiUA** [formio/formio#1441]
If you try to use this https://pro.formview.io/#/test-arbostar-state/pdftest1testcompany?header=1&reset=1 from mobile or simply enable dev tools, you will be able to see that you can't simply sign anything. This only appears only on pdf forms.

**Comment by travist** [comment]
The "pdf-first" forms are pixel perfect forms. This is GREAT for the use case that you wish to show the form "as-is" to the end user. However, it DOES NOT work responsively (since it would no longer be pixel perfect), so your use case is invalid. If you wish to have a "mobile" view of this form, then you can just change the display of the form to "form" but keep the pdf attached so that they fill out the form with the responsive form, and then when they print, it will print as pixel perfect.
