### ISSUE TITLE
[BUG] Green `Submission Complete` always appears when `formio.fetch()` is called

### ISSUE THREAD

**Issue by bilogic** [formio/formio#1474]
## Environment
Please provide as many details as you can:

https://formio.github.io/formio.js/app/examples/customendpoint.html

## Steps to Reproduce
1. After clicking the form, a green `Submission Complete` is always shown before the server responds.
2. It seems that once `formio.fetch()` is called, this green message appears.
3. This green message can mislead user into thinking all is good.

## Expected behavior
When `form.nosubmit = true;`, no prompt/message should appear until custom code parses the server's response

**Comment by bilogic** [comment]
I realized in the settings of buttons, there is a `POST to URL` option, which solves the problem, but introduces another security related issue of not having CSRF tokens.

Instead of rewriting the whole XHR request like shown in the example, is there a way to inject a header using javascript at runtime?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
