### ISSUE TITLE
Don't fire validation when submit using submit_edit 

### ISSUE THREAD

**Issue by daanishlive** [formio/formio#1566]
how to stop the form validation when submit through submit_edit button provided by FormIO

**Comment by DeekshithRajBasa** [comment]
Hi @daanishlive, in order to assist you better and provide a solution to your issue, I kindly request that you provide additional information. It would be helpful if you could include screenshots or a detailed description of what you are trying to achieve. This will enable me to better understand your problem and offer appropriate guidance. Thank you!

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
