### ISSUE TITLE
Delay in sending email after Submitting a form.

### ISSUE THREAD

**Issue by koteshgangavarapu** [formio/formio#1666]
Hi,
I have configured an email action so that email gets generated after form submission. Email action is working and I do get the email as expected. However, the email is delayed by approximately 16 minutes. I have enabled action logs and found that there is a gap of around 16 minutes between "Action Resolved(no longer blocking)"  and "Sending message" in action logs. Anyone else facing the similar issue? Any suggestion? I have tried this with different email providers and facing the same issue. Attaching the screenshot of the action logs for reference.  
Using formio-enterprise:8.1.0 version. Also tried with formio-enterprise:8.1.0 as well and facing same issue.
![Email actionLog](https://github.com/formio/formio/assets/87490598/997730dd-067c-440b-9f7a-9ca526a47ab7)

**Comment by brendanbond** [comment]
What does your email action entail? There was an issue where database queries that involved case insensitive searching (so, things like certain SSO actions, username lookup, etc.) may not be performant given a large dataset because MongoDB indexes don't really play nicely with case insensitivity. In newer versions of the Enterprise Server we've done some work to use collation-aware indexes to speed that up by quite a lot.

If it's just a normal email action, can you post its JSON schema?

**Comment by brendanbond** [comment]
Great! Yes, it will fall back to the "message" property of your email action configuration without a surrounding template. I'm glad this got resolved.
