### ISSUE TITLE
npm install instruction

### ISSUE THREAD

**Issue by erikpb** [formio/formio#1702]
The documentation specifies:
- clone the repository
- inside the folder, on the host, run `npm install`
- run docker compose
Would it not make more sense to do the `npm install` inside the Docker container? Otherwise the node packages that are installed will be the ones determined by the host OS rather than the container OS?

**Comment by brendanbond** [comment]
That's what [it already does](https://github.com/formio/formio/blob/4999aa8a4df8e691a0731efd2cb26f54c0cc397c/Dockerfile#L36), it just uses the generated package-lock.json file to "freeze" dependencies. I'm looking into whether this is compatible with some new dependencies that we've added (and node-gyp, etc.) and if it's even necessary any more (it seems like it and some other weird install stuff e.g. ./npm-packages virtual directory were workarounds, hopefully they're no longer an issue). I wonder if the issue is that package-lock.json contains host specific binary info? In any case, this will hopefully be resolved soon

**Comment by brendanbond** [comment]
Hey @erikpb I've gone ahead and opened #1703 that addresses your suggestion. Take a look and let me know your thoughts.

**Comment by erikpb** [comment]
That fixes the issue @brendanbond, thank you very much.

**Comment by codespearhead** [comment]
@erikpb It seems that #1703 was recently merged. Should this issue be closed?

**Comment by erikpb** [comment]
Yes please.

**Comment by erikpb** [comment]
Closing.
