### ISSUE TITLE
Duplicate labels on HTML component in 

### ISSUE THREAD

**Issue by jackhulbertpdx** [formio/formio#1816]
**Describe the bug**
I am embedding forms from my application. Upon new submissions, HTML components render with duplicate labels. I am using these HTML components out of the box with no custom behavior.

**Version/Branch**
v9.2.3: formiojs@4.21.4

**To Reproduce**
1. Create form...
2. Add HTML component...
3. Embed form into application

**Expected behavior**
There should not be duplicate text.

**Screenshots**
![image](https://github.com/user-attachments/assets/4902cea5-d229-43ef-be52-96d8ec251753)

**Additional context**
I am using Form.io, cloud hosted.

**Comment by lane-formio** [comment]
We have expect this to be fixed in our upcoming 9.3.0 release, and in the meantime we worked around this by changing the parent tag on our html components from "p" to "div" and then had to remove any html content that was registering as invalid.
![image](https://github.com/user-attachments/assets/de45fb47-a1fc-469f-bc11-1a9ba4780567)
