### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by deonvisser** [formio/formio#224]
Hi
I am getting the above error in the browser console when trying to use the API.It did allow me to create a user first time and I can use this user to login but it seems any other data access is unauthorized. This is preventing the creation of new forms.

Do you have any documentation configuring and using this API? It only seems you have docs regarding your main application and nothing on formio on github?Please excuse my ignorance if I am wrong.
Thank you.

**Comment by zackurben** [comment]
Hey @deonvisser, the issue is the default permissions configuration. By default, only the primary account should be able to create new forms (When you installed the app, you configured a primary account user).

If you're trying to create form submissions with your new app user, verify that the user has create_own or create_all permissions.

No, you are correct. We don't currently have explicit documentation for this repo, and the docs on [help.form.io](https://help.form.io) are a superset of the functionality here; maybe we can start the wiki pages?

**Comment by deonvisser** [comment]
Hi @zackurben 

Thank you for your reply, but I am totally  lost. I don't understand the concept and am looking for stuff but cant find anything that makes sense to me. I need docs to explain the concept and connectivity.  If I understand,  the repository should be the mongo formioapp  db? I have a user that is created at http://localhost:3000 but have no idea where it was created as there are no users in the mongo formioapp db? Should this user not be created there there? Where do I verify that the user has create_own or create_all permission as you indicate?

Thank you.

**Comment by todduk** [comment]
@deonvisser 
Did you find more info anywhere? Struggling with the same 401 errors everywhere myself.
