### ISSUE TITLE
Class on input instead of wrapper?

### ISSUE THREAD

**Issue by peterbrinck** [formio/formio#237]
Hi!

I recently started using Form.io, hosted on my own server.
Everything works great, but is it true that I can't add classes to the input fields, only to the wrapper?

It's way easier to add classes to the input itself, in my opinion (and in my setup).
Sorry if it's in the docs somewhere, I just wasn't able to find it.

**Comment by zackurben** [comment]
Hi @peterbrinck, right now there is not a supported way to add css classes to individual input elements. This is due to the fact that each component doesn't necessarily equate to one html input element, for example components with labels and stuff.

You could do some hacking of ngFormio and ngFormBuilder to override the html templates in the template cache, but you could face other issues.

Additionally each parent dom element has a specific selector, so you can use some more advanced css selectors to modify the style of individual child dom elements.

Hope that clears things up a bit,
Zack.
