### ISSUE TITLE
markdown component support

### ISSUE THREAD

**Issue by ericdai** [formio/formio#258]
like editor.md or other markdowm editor

**Comment by travist** [comment]
Right now we do support WYSIWYG capabilities through a configured textarea component with the flag "wysiwyg = true", however, that is a front end capability. This repo represents the API platform behind the front end mechanics of form.io, so I don't see us adding this capability here. This can be done within the application sitting on top of this API platform.

Closing since we won't fix this within this repo. Good suggestion though.
