### ISSUE TITLE
Multi-Step Form Rebuild Considerations

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#296]
WIP.

This is a working list of considerations for Multi-Step Forms:

1. Be able to go to a external page and have a call back to the step that the user was on before going to the external page.
1. be able to get a current step information such as:
   1. Last Step
   1. Current Step Number
   1. Total Steps
   1. Number of steps left
   1. ...
1. Optional Steps that are shown in the Step List but possible to Skip.
1. Optional Steps that are not shown in the Step List Until they are used
1. Optional Steps that are not shown in the Step list at any time.  (Example, a Error Step that stops the flow from moving forward)

More to come

Some of the inspiration: https://github.com/craue/CraueFormFlowBundle See their readme.

Other possible node inspiration or reuse:  These example sare actually from UK gov:
https://www.npmjs.com/package/hmpo-form-wizard
https://www.npmjs.com/package/hof-form-wizard

Working List of Considerations:

1. Error Handling
1. Per-Step Server-Side Validations
1. Per-Step Server Delivery of next step's form
1. Session Expiration: per-step, and On final submission
1. Should a Multi-Step Flow be built from Many different Forms?
1. Supported Back Links Per-Step (when on Step X, what other Steps can you go back to)
1. Step Branching
1. Calculation of N of N steps in a wizard
1. translation support
1. Reset Journey/Form ability
1. Save for Later on Per-Step (Forced)
1. Save for Later on Any Step (optional)

**Comment by travist** [comment]
Here is my proposal for implementation of this feature. My goal is to achieve this while maintaining the "stateless" aspects of the platform. This means that most of the logic will actually occur in the front end libraries, while the backend API may need to be altered just slightly.

I believe we can accomplish everything you need by introducing 3 new features in the platform.

1. **Form Component** - This will be a new component that simply embeds an existing form within another form allowing for nested form interfaces. This component would become critical to this feature since it will also allow for dynamic loading of forms in realtime as a user is stepping through their "dynamic" wizard. When the next page is triggered, this component will trigger an actual form submission in that embedded form, and save the submissionID of that nested form as the value for the field of the component.

2. **Dynamic Next Page** - I think this could be a setting on the Panel component that allows for a JavaScript script to execute to determine the next page. The next page value would simply be a "string" that is the API Key of the Panel which should come next in the flow. It would look something like this.

```
var next = (data.foo === 'bar') ? 'barpage' : 'normalpage';
```
This would then set the next page to the ```barpage``` if the value of ```foo=bar```. Combine this with the previous feature, and you can achieve dynamic form loading per page.

3. **Submission Drafts** - This would require a change to our backend API, but it is a simple change. We will basically create Submissions that are in ```draft``` mode which means they will not show up in the submission index. This works similar to how our ```deleted``` flag works, but instead of being deleted, the submission is in Draft mode and can be restored by the front end application by providing the ```?draft=true``` query argument to the url. This would allow the "wizard" to save its current submission for every page in the wizard as a draft submission for that wizard. It should also be noted that the actual submissions would end up getting saved in the "sub" forms that are created from the Form component proposal of 1.).

With these three things combined, I believe we can achieve a VERY powerful and flexible dynamic wizard platform. The final submission for the wizard would look something like this.

```
{
  "data": {
    "page1": {_id: "2234234234234234", form: "234234123123123"},
    "page2": {_id: "2234234234234234", form: "234234123123123"},
    "page3": {_id: "2234234234234234", form: "234234123123123"}
  }
}
```

You could then review this submission by "lazy-loading" the submissions as they navigate the wizard. You could also create a "view whole" submission feature which would flatten all the panels and then load the submission sequentially providing a "stateless" way to accomplish a very scalable system.

Thoughts?

**Comment by StephenOTT** [comment]
>When the next page is triggered, this component will trigger an actual form submission in that embedded form, and save the submissionID of that nested form as the value for the field of the component.

@travist how would going back in the form change this?  The user would be able to overwrite draft submissions?

**Comment by travist** [comment]
> @travist how would going back(going to previous step) in the form change this? The user would be able to overwrite draft submissions?

The wizard keeps track of a stack of pages as they are being navigated. As they go back to a previous page to make a change, and then move forward again, they would then UPDATE the draft submission being made in that form. This would perform the server side validation for that specific page even for updates since that form would be re-validated on the UPDATE request.

> @travist This logic is executed on the Server Side with the Server looking at the values of the draft submission?

The server should not care about the "wizard" or "flow", "next" or "previous". This maintains the statelessness of the server. The server will validate each page in the wizard due to the form actually being submitted, but that is done from the wizard controller in the front end. The wizard controller will then decide what is the next form to be submitted. It also should be noted that the "wizard" is actually a form in itself made up of Panels that themselves point to separate forms. Think of it as a linked list, but the determination of the "next" page is done on the front end not the backend. Hope this clears stuff up.

**Comment by StephenOTT** [comment]
>The server should not care about the "wizard" or "flow", "next" or "previous". This maintains the statelessness of the server. The server will validate each page in the wizard due to the form actually being submitted, but that is done from the wizard controller in the front end. The wizard controller will then decide what is the next form to be submitted. It also should be noted that the "wizard" is actually a form in itself made up of Panels that themselves point to separate forms. Think of it as a linked list, but the determination of the "next" page is done on the front end not the backend. Hope this clears stuff up.

If the logic of "what page comes next" is executed on the front-end, then the client is able to access any step.  The purpose of server-side validation of each step is to ensure that the delivered form is only accessible if the step validation is correct:

Scenario 1: Page 1 -> Page 2 -> Page 4 -> Finish
Scenario 2: Page 1 -> Page 3 -> Finish

Page 3 should be able accessible by the client in scenario 1.
Page 2 and Page 4 should not be accessible in scenario 2.

If i understand your proposal, these two scenarios are not possible.  The system can remain stateless if the logic is executed on the server.  No session is stored.  It is just the evaluation of the rule is executed on the server based on the submission draft's data

**Comment by GuillaumeSmaha** [comment]
Scenario 1: Page 1 -> Page 2 -> Page 4 -> Finish
Scenario 2: Page 1 -> Page 3 -> Finish

The next function could return a `false` value to define a submit button

    var next = (data.foo === 'bar') ? false : 'normalpage';

If `foo=bar` then display a submit button instead of a next button for the page `normalpage`

**Comment by StephenOTT** [comment]
@travist if we assume that having multiple Form submissions (1 per page submitted) as a good pattern based on how Formio currently functions,

And Form Component is useful for a few different use cases,

But the Next Step Logic that is still being executed on the client side is problematic in how i understand it.  Your proposal seems to limit the amount of server edits required, but it also means we are doing client next step calculations client side and those can be "hacked" to retrieve any step they wish. (which means the original purpose for the server-side validations is lost).

Right now Panels are embedded without the form construct.

What is a new construct was created that lets someone build individual forms (as formio currently does), and the new construct was a PageFlow construct that allows someone to chain together the individual forms.

This would provide the ability to create multi-step forms that have client side and/or server-side logic on the next step actions.


---

Another question, how do you propose the drafts get consolidated?
Consider the following scenario:
Full Journey: Page 1 -> Page 2 -> Page 3 -> Finish.

Page 1 -> Page 2 -> Page 3 -> Back to Page 1 and make an edit. -> Because of edit of Page 1, you skip page 2 and go to Page 3 -> Finish.

In this scenario you submitted data for page 2 but then post-submission you went back to page 1 and made a change that invalidates page 2/you skip page 2.  So how would you consolidate this change and represent it in the from data submission of forms?

**Comment by travist** [comment]
@StephenOTT I don't think that having a concern of someone hacking the renderer to produce the "flow" they want is a feasible concern. The deployed wizard logic that governs the flow will be obfuscated and will be executed and control which page is shown next. As the developer who wrote this system, not even I am sure how they would be able to alter how they would hack the flow. It would actually be easier to hack if it were controlled on the server since the "next" step is part of the schema of the form and that could be intercepted before being sent to the server.

If that is a legitimate concern, then the wizard flow could not be attached to the schema of the form (which I am not a fan of).

**Comment by travist** [comment]
Hello everyone. I wanted to let you know that the preliminary version of this is now available with the latest core renderer. Here is a demo of it working.

http://formio.github.io/formio.js/app/examples/multiform.html

Thanks @GuillaumeSmaha for the initial development of this. Right now, we have both dynamic next page as well as the Form component which is what enables this capability.

**Comment by tiwana007** [comment]
Following from the package.json and bower.json -
"name": "formio-app-formio",  "version": "1.3.0"
"ng-formio": "^2.22.5",
 "ng-formio-builder": "^2.22.3"
"angular": "^1.6.6"
I have the following two issues in this space:

1. Validations on current page get executed when user navigates to PREVIOUS page - 
this is not user friendly especially where the user needs to edit a field on the previous page. If the current page has 20 mandatory fields then all the fields must be completed before the user can return to the previous page to make the desired change.

2. When using form wizard, the fields within a data grid do not get highlighted when a infield validation error occurs on submission or moving to next or previous page.

A error message gets displayed on top of the page "Please fix the following errors before proceeding". This is true ONLY the errored field is in a data grid AND when the form is in wizard mode. So while in wizard mode, the validations are getting executed but there is no way to determine which field errored. #
![33321887-ff27fc18-d492-11e7-8ee2-a3f8c73d619b](https://user-images.githubusercontent.com/33194378/33422987-41d6571e-d603-11e7-97e4-28f0689a71e1.PNG)
![33322073-accee890-d493-11e7-8253-36ba7b3001a6](https://user-images.githubusercontent.com/33194378/33422990-43cf189e-d603-11e7-984b-213dfad843d9.PNG)
![capture](https://user-images.githubusercontent.com/33194378/33423135-ada63c7a-d603-11e7-9010-2cc235e48ea4.PNG)

**Comment by StephenOTT** [comment]
Hi! 
Was there any progress in any of the above?

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
