### ISSUE TITLE
Issue with fresh install in windows 10

### ISSUE THREAD

**Issue by csciallano** [formio/formio#386]
Hi, i wanted to try this framework for dev purposes but i can't get it to work. Maybe somebody had a similar issue...
I have python 2.7, npm and node up to date.
I have the windows production tools installed and ran npm install
No problems during installation except 1 optional dependency skipped

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})

I attach the npm debug log
[npm-debug.txt](https://github.com/formio/formio/files/1169126/npm-debug.txt)

Thank you very much !

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
