### ISSUE TITLE
Rendering Wizard Issue - Help Requested

### ISSUE THREAD

**Issue by rogerconner** [formio/formio#389]
Using the form builder on web Form.IO there is no option to switch to the wizard designer like there is when you run the form builder locally. 

In addition, it mentions that it is using the panel class to determine the wizard steps. I have been unable to get the wizard to render using the web Form.IO builder. 

It does not even render when using the hosted formview when setting the wizard state to 1 and it references formio-wizard which has been merged into the core renderer.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
