### ISSUE TITLE
Can't login to Form.io API

### ISSUE THREAD

**Issue by Arifi** [formio/formio#428]
When i run `npm start` then i provie email and password, i can't login to the API platform (port : 3001), but i can login with same creentials to application (port : 3080)
I missed something ?

```
Importing template...
Creating root user account...
prompt: Enter your email address for the root account.:  mou@rad.com
prompt: Enter your password for the root account.:
Encrypting password
Creating root user account
Install successful!
 > Serving application at http://localhost:3080
 > Serving the Form.io API Platform at http://localhost:3001
```

**Comment by Arifi** [comment]
any help ?

**Comment by A-Pradeep** [comment]
can you reinstall the  form.io from scratch and lemme know if you face the error again , because i'm using the Form.io Open Source code itself and never came to this problem.
& make sure you give the same exact credentials like Email Id and the Password for the login purpose , which given earlier at the prompt.

**Comment by sdancer75** [comment]
I droped the formio db and I re-installed. I meet the same problem. Any solution to this?
Question : Where the root account is stored inside the DB?

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
