### ISSUE TITLE
Posgressql support in formio 

### ISSUE THREAD

**Issue by amithole1987** [formio/formio#510]
Hi,

I have download formio for form builder and form storage management. It working fine with mongo database for storing the forms and resource with authentication.
We need the support for postgres sql database support.

What I am trying to achieve is by adding the node package for pg.
Please help me out

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
