### ISSUE TITLE
Integrate form.io with flowable

### ISSUE THREAD

**Issue by WWWW-W** [formio/formio#524]
Hi, has anybody done a project to integrate form.io with flowable (A business process management engine). In the form design section, I want to substitute the form designer of the original flowable with form.io.

Or I wonder if after saving the form builder of form.io, can it output the json data of the form?

Regards,
Ziwen

**Comment by andresetevejob** [comment]
Hi,it's my challenge today.
Can we share our experience,if you want

**Comment by bhanu-singh** [comment]
Hi guys I am also trying to do this any help will be appreciated.

**Comment by aiwebb** [comment]
The JSON for each form is available via this button, located next to the form title in Builder view:
![image](https://user-images.githubusercontent.com/1616716/59202117-7571ed80-8b61-11e9-9d18-936927200e97.png)

**Comment by ChinaShrimp** [comment]
good idea!

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
