### ISSUE TITLE
Theme documentation: does it exist? (I couldn't find any)

### ISSUE THREAD

**Issue by tbredin** [formio/formio#534]
I wasn't able to find any documentation amongst form.io docs that outlined that it used bootstrap 3.3.7, or instructions for setting up a custom bootstrap build to customise the skin of form.io. These would both be great to see for future users!

I'm still currently unclear whether or not there's any configuration options for theming (eg: I'd love to use 4.0 if it might become supported in future)

**Comment by jhen1422** [comment]
Hello Thomas,
 
Jeriah here from the support team. Thank you for reaching out.
 
We appreciate your feedback. Documentation is something that we have prioritized and currently working on.
 
For the time being you can watch our Angular 5 tutorial here :
 
https://www.youtube.com/watch?v=zEvzW_sSXk0&t=401s 
 
which showcases a Form.io application built using Bootstrap 4. 
 
https://github.com/formio/angular-app-starterkit
 
These two videos should give you the information you’re looking for.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
