### ISSUE TITLE
Form.io not works with React 16 component

### ISSUE THREAD

**Issue by bionicvapourboy** [formio/formio#543]
React component does not works with React 16 and no one is taking care of managing issue on the repo, the component needs simple changes to get ready with react 16 but no one seems care of it.
I write here because my customer run an enterprise service based on your platform and I need to know if development and updates are solid or if I have to suggest to switch to another service.

**Comment by mrbarletta** [comment]
I read an email from them saying they are rewriting formio on vanilla JS with some extension support for angular/react/vue etc. So they must be very busy.

Having said so, we were in a similiar situation and we stopped using this awesome piece of software  (used react too) due to almost no show on github issues, poor documentation, and no community built around it. It has tremendous potential for small to large businesses so I really wish they succeed.

So

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
