### ISSUE TITLE
Add API for getting clean submission data [Feature Request]

### ISSUE THREAD

**Issue by sathiz1993** [formio/formio#547]
Since the current API for getting submission returns data in nested JSON and array which contains data and also metadata **(http://{{appUrl}}/register/submission/{{submissionId}})**, I need a data which returns cleaned key-value pairs of all the fields of the submission

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
