### ISSUE TITLE
Persistent field VS Required

### ISSUE THREAD

**Issue by marioprudhomme** [formio/formio#563]
Currently, when I set a form field to PERSISTENT=FALSE and REQUIRED=TRUE, the required validation goes back to FALSE. 

From my end, it seems like the PERSISTENT option overrides the REQUIRED option.

I believe the field should still be required and issue a validation error message at the API level.

This is a use-case for us because we use various storage (and not just formio's)

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
