### ISSUE TITLE
Unable to log out

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#568]
If you run /logout you get a OK response but the jwt is not deleted and the user is still logged in.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
