### ISSUE TITLE
Add ability to modify Submit Form button when using Wizard builder

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#569]
The wizard builder does not allow the user to edit the Submit Form button. This should be configurable in Wizard mode

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
