### ISSUE TITLE
Increase default number of shown forms in main admin page

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio#571]
Currently the default list only shows 5 forms.  It should show more forms such as 25 or 50.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
