### ISSUE TITLE
Stateless Formio

### ISSUE THREAD

**Issue by pixie79** [formio/formio#574]
Hi,

It would be good if we could remove the requirement for running Mongo and either directly have the forms stored on something like s3/Minio. The forms could be loaded into cache for faster load times. The other option would be to allow you to post a form to the API at the same time as validating the content and have formio do the validation.

We are looking at that as we intend to run formio inside of a kubernetes docker container with no state stored other than on s3.

Our only other option is to run an init container that upon boot pulls the forms from s3 and pushes them into the API.

Regards

Mark

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
