### ISSUE TITLE
Persistent Flag for Content Component

### ISSUE THREAD

**Issue by SamWij** [formio/formio#575]
Currently content components are displayed as a column in form submission for Wizards.  There should be the ability to flag these as not Persistent similar to other components such as the radio component.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
