### ISSUE TITLE
Unique multiple fields

### ISSUE THREAD

**Issue by tmdoit-zz** [formio/formio#598]
How can I set to unique at least two fields of the resource row?

**Comment by tmdoit** [comment]
I've did this by setting unique keys in database but don't know how to handle those errors on client side (change raw mongodb error message to something user friendly).
I can add a before submit validation but this is an odd solution for customising only an error message.

**Comment by luislobo** [comment]
@travist Is there a recommended way to handle Records where the primary key is composed of multiple fields?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
