### ISSUE TITLE
Access resource fields in components custom logic

### ISSUE THREAD

**Issue by tmdoit-zz** [formio/formio#599]
How can I access in custom logic different resources and its records and fields?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
