### ISSUE TITLE
Just want to confirm this open source version do not have project/form permission?

### ISSUE THREAD

**Issue by kamanwu** [formio/formio#604]
I only saw submission permission.

I did not see projects and form related permissions.

Is there anyone can confirm it?

**Comment by shervud** [comment]
Seems I have the same question.
I tried to make a POST request to http://localhost:3001/project , as it is said in API docs here https://apidocs.form.io/#a7ca9883-4ec4-5226-f36c-a6dd0d0727f3  but I always get the error "Invalid alias". Also I have noted that all the API methods given in the API documentation (https://apidocs.form.io/) that starts with "{{**api**Url}}" do not work and it ends up with the errors of different types... but most frequently these errors are "Invalid alias". While the rest of methods starting from "{{**app**Url}}" work properly.
Could anybody tell please, is it OK? Why does it behave that way? Is this because current formio api is just a core and does not provide several features like they are in Enterprise versions (https://help.form.io/userguide/environments/#environments).

**Comment by shervud** [comment]
Also I cannot configure CORS settings as they exist in portal.form.io and so on. So I feel like it is somehow connected with that fact that current formio repo has only core stuff and does not include the rest of things that currently exist on portal.form.io. Am I correct?

**Comment by randallknutson** [comment]
The open source server does have form permissions. We haven't exposed the settings in a tab in the formio-app-formio application which is installed at runtime. You can add this page yourself if you want. There are no projects nor project permissions though.

**Comment by shervud** [comment]
Thanks

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
