### ISSUE TITLE
Select boxes not rendering

### ISSUE THREAD

**Issue by CardwellSportfishingClub** [formio/formio#611]
Hi, the select boxes are not appearing on my form.  	

		<section id="cta" class="wrapper style4">
			<div class="inner">
				
				<div class="form">	<h2>Membership application form</h2>
					<p>Please complete all fields</p>
				
			<script src="https://unpkg.com/formiojs@latest/dist/formio.embed.js?src=https://agdfdljvoreyatj.form.io/membershipapplication=1&theme=superhero"></script>
			</div>
				</section></div>

Is it because of the CSS?

Thanks 

Susan

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
