### ISSUE TITLE
formio select box value not being set properly.

### ISSUE THREAD

**Issue by saurabh1294** [formio/formio#619]
Hi,

When I try to set value in select box of form.io , its not being set properly. Please advice how to change values in form.io dropdown select box.

Thanks,
Saurabh

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
