### ISSUE TITLE
Handle Custom Event in JSOn

### ISSUE THREAD

**Issue by devesh23** [formio/formio#642]
@travist How to handle custom events in JSON such as onClick, onBlur, OnFocus

**Comment by shivlila01** [comment]
We are also looking for the same. Refer https://github.com/formio/formio/issues/684
Please let us know if you found any solution for this.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
