### ISSUE TITLE
How to Integrate Form.io in Mobile application?

### ISSUE THREAD

**Issue by Saravana181187** [formio/formio#666]
I have developed the native mobile application in iOS, Here I want to integrate form.io in my application but I don't know how to Integrate and what are the ways for Integrate?
Please can you give some idea for my problem?

**Comment by wag110894** [comment]
Hello Saravana,

This is William with the Form.io support team.

Thanks for reaching out! 

We would love to connect hear about your project and see how we can help.  We provide community support and also have support packages available for training, support or development services if you are interested! 

Thanks, 
William Gay 
Form.io Developer Support

**Comment by Heja0007** [comment]
Hi @Saravana181187 .any updates on this mobile app? i am trying to integrate form.io on my app too.
Thank you

**Comment by bendrda** [comment]
My understanding is that Form.IO has a few renderers: Angular, Vue, etc. and that none of these would translate well to a _native_ Android or iOS application. 
Since the only current renderers are web-only, they do have instructions for embedding the form.io via a Cordova webview: https://help.form.io/developer/cordova/

**Comment by randallknutson** [comment]
The closest we have at the moment is the react-formio-native renderer which contains about 2/3rds of the components that will render in react-native.

**Comment by bendrda** [comment]
@randallknutson Is that an active repo? Last commit was 9 months ago.

In any case, the repo itself tells us not to use it.

**Comment by travist** [comment]
The last commit was 2 days ago.  What exactly are you looking at that gives you the impression this repo is not maintained?

https://github.com/formio/formio/pulse

**Comment by ChamMya2620** [comment]
hi all, please help me!.
i user formio in native kotlin android.
i reference this document,
***
https://decode.agency/article/form-io-in-native-android-application/

****
i do not Validating and collecting form data. 
if you have  test app gethub using formio , please give me.
thanks you .

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
