### ISSUE TITLE
Custom Button not working in the Rendering/Embedding

### ISSUE THREAD

**Issue by A-Pradeep** [formio/formio#674]
Hi, i have a custom button , which clear the values / reset the particular component.
` i.e. data.firstname=''; `

It works fine inside the Form.io Online / Open source . But  when it comes to the Rendering/Embedding side , it wont work at all. Even there is no error in the console.
I tired this on the Form.io Online portal , and i  found out the same problem.
It works fine when we view the form in the  [`Form Viewer` ](https://formview.io/#/qfeuvqlfrsmdign/message&header=1) , but when we use the single line `script tag` inside the `HTML` , its not working .

`<script src="https://unpkg.com/formiojs@latest/dist/formio.embed.js?src=https://qfeuvqlfrsmdign.form.io/message"></script>
`
I think the embed.js has missing  some functions .
Any ways to solve this Issue.

And i wanted to know much more about the `Actions` in the Button ,
Like Event , Auth etc. I didn't find much more information about these usage . Any information provided would be a useful.

Thank You

**Comment by wag110894** [comment]
Hello Pradeep, 
We are unable to replicate this issue on our end. Here is a screenshot of this working for us.
https://www.screencast.com/t/9MCAMkRoLtHm 
What browser are you using? We have testing on Angular/Latest Core on Chrome/Safari/Firefox.   
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by wag110894** [comment]
Hello Pradeep,

You cannot use a button using custom javascript to change another component’s value in our new renderer.  This is by design. You can use a button event and field logic to set the value. 

Here is an example of this: http://formio.github.io/formio.js/app/examples/fieldLogic.html 
Here is schema for Field Logic: https://github.com/formio/formio.js/wiki/Field-Logic-Schema 
Please let me know if you have any further questions or concerns.

Thanks,

**Comment by A-Pradeep** [comment]
Hello, but the same code works fine in the formView.io and any ways i can use the previous version of the render  since due to the new renderer most of the components not working properly (like the Reset Particular Button , and Calculated Number Field ) and it will take more time for redo the changes .

It would be  great if the old functionalities are put in the new renderer. Because it's easy to code inside the Custom code  rather than doing this Event and field logic . 


What is the use of Custom Properties in the API , since i didn't find out much about this in  the Documentation.

**Comment by travist** [comment]
There are several issues that arise when allowing one component to alter the state of other components (as it is suggested here). 

1.) The state of any component is mutable by other components and conflicts in state changes can cause erratic behavior such as when one component sets the state of one component to one value while another component sets it to a different value.

2.) Performance is negatively affected where all button events would need to trigger global form redraw since it would be hard to determine from reading custom code which components may be affected by the change.

We are deliberately making this not supported via setting the data attribute. However, there is a way to "break the rules" if you insist. In every code execution, we do provide the ```instance``` variable which points to the component instance. Within the ```instance``` you have access to the ```root``` form object, which is the most top-level component of a rendered from. From that perspective, you can then get the component you wish to alter, and set the value directly. Something like this may work.

***Use at your own risk!!***
```js
var component = instance.root.getComponent('componentA');
component.setValue('testing');
```

**Comment by A-Pradeep** [comment]
@travist  Thank you so much for the detailed answer and i'll keep this in mind

**Comment by A-Pradeep** [comment]
@travist @randallknutson  Hi, im facing some issues with the number component.
The calculated value is not appearing in the form rendering ! .
I have a `Number field` component which show the calculated value and a `Radio Button` , 
if i click `Radio1` then value is 5 , `Radio2` then value is 10  should be shown in the `Number Field`etc.
I have to refresh several times , then can see the value. correctly.
I don't see any errors in the  `console` too.

**Comment by randallknutson** [comment]
Can you re-read Travis's comment? He showed a way to do what you are asking for.

**Comment by A-Pradeep** [comment]
1. @travist @randallknutson   Hi,  how can i print the `Label` (value) of the Select Box or at least the Value of it. Inside the HTML , if i give `data.page1SelectBoxes` the response will be `[Object][Object]`.
If `data.page1SelectBoxes.check1` then response will be `True or False`. Is there any way i can print the value of it , rather the  the `True or False` .

2. Is there a Form Submission Date for each submission, how can i access it .(like {{submission.created}} ?)

3. In the Email Action , the  `Email Template URL` is not working. I wanted to know how does it actually work.

![selectbox](https://user-images.githubusercontent.com/37439293/47981737-104da980-e0f3-11e8-8093-9e6c17b3e65f.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
