### ISSUE TITLE
"Save as Reference" saves the full data to the DB instead of just the ID

### ISSUE THREAD

**Issue by olsn** [formio/formio#717]
This is probably just a minor issue, as it is not causing any visible effects:

On a new (or existing form):
1. Create a select-component (or resource-component)
2. set it to "Safe as reference"
3. set it to "Allow multiple selected"
4. set it to any resource (tested with different resources, seems to be the same for any)
5. save
6. create an entry with this form (of course you have to enter some data in the select- or resource-component)
7. check the submission in the mongodb -> the mongo-document contains the whole resource inside an array, not just a reference-id as I would have expected.

Not sure if this is a feature by design or a bug. It doesn't make a difference in the UI, there is no visible affect of this in the frontend, it just seems to clutter the data and I was a little confused when investigating the database-contents.
Tested with version: 1.37.5

**Comment by travist** [comment]
We will add this as a bug in our backlog, but you are correct and assume this is probably a minor.

**Comment by HaidarZ** [comment]
One year later , still the issue has not been taken into consideration.

**Comment by wag110894** [comment]
@HaidarZ, 

This item is still on our backlog. We welcome a pull request or have a process to expedite this issue if you are interested.

Please contact support@form.io if you are interested in expediting.

**Comment by ZenMasterJacob20011** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
