### ISSUE TITLE
Fields are getting distorted on the android device

### ISSUE THREAD

**Issue by akhilesh-sharma168** [formio/formio#731]
Hi Team,

Tested on Samsung Galaxy Note 8 .
The form fields are getting distorted on the mobile device.
Can you look into the issue. For the same I have attached the screenshots.

![20190204_151208](https://user-images.githubusercontent.com/45589364/52200655-5ef41680-288f-11e9-8760-7700a7da810e.jpg)

**Comment by travist** [comment]
This looks like custom styles have been applied to this form. Can you verify if there are not any other custom styles being loaded with the form? We just use standard bootstrap styles for these fields so it should be vetted and look good for all devices.

**Comment by akhilesh-sharma168** [comment]
Hi @travist ,

I gone through the css styles sheets to find the custom css , but I couldn't find it . Can you just look into your part of css, that has been added to make it compatible with the default bootstrap styles.
I have attached the desktop version of same form , which looks fine.
![desktopversionofform](https://user-images.githubusercontent.com/45589364/52257069-2a3f9800-293f-11e9-8a53-96152242a7e1.png)

**Comment by akhilesh-sharma168** [comment]
Hi @travist 

Did you get the chance to look into the issue?

**Comment by randallknutson** [comment]
There really isn't a lot for us to look at on our end. This is more than likely a CSS styling issue you can fix within your own application. One thing to note is that Tables and Datagrids (which use tables) don't typically work well on mobile since they allow building forms that are wider than the phone screens. You are better off using columns and editgrids instead.

**Comment by ZenMasterJacob20011** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
