### ISSUE TITLE
Sequence number

### ISSUE THREAD

**Issue by bigjorjao** [formio/formio#738]
I have a need to create a field in a form that is like a sequential number. 
I've been investigating and can not find a way to do it. How to implement?

And if i have a datagrid how implement for exemple.

nº of auditory || description ||start date || end date

where nº of auditory is the number sequential for this collection. Is possible?

**Comment by randallknutson** [comment]
We don't currently have a way of having sequential fields. This is because in progressive web app the submission isn't created until it is finished and sent to the server. Therefore we can't assign a sequential id until too late in the process.

However, in a datagrid there is a rowIndex variable available that you can use that is the index of the row. In the auditory field you can set the calculated value to "value = rowIndex" and see if that works.

**Comment by ZenMasterJacob20011** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
