### ISSUE TITLE
ES5 to ES6

### ISSUE THREAD

**Issue by kmgilbert100** [formio/formio#74]
If this is a new revolutionary peace of software why isn't it written in ES6 and compiled in babel awaiting for the official release of Node 5... or if you want to say a Javascript engine that actually processes ES6 fully.

https://babeljs.io/

Keep up with the times ;) - There plenty of reasons you may not have wanted to use this but I would love to be educated on the reasons?

**Comment by travist** [comment]
We are familiar with Babel + ES6 and have written some of our plugins utilizing it. 

We didn't use it for this library simply because it was not considered stable for production use until June of last year. We had already written a significant portion of this library developed by then and did not want to base our initial version on a library that was still considered alpha version. So when you say "keep up with the times", you are really asking us to keep up "6 months". I understand things move fast in the world of software, but we have to be pragmatic with our release schedule and priorities. Right now, there is really not a big enough reason for us to upgrade other than the desire to keep our codebase updated with latest versions.

With that said, it is Open Source. We will happily accept pull requests to get library updated with ES6.
