### ISSUE TITLE
Same submission repeats

### ISSUE THREAD

**Issue by NiMusco** [formio/formio#741]
Hey!

I'm having some trouble, both API and GUI.
When getting a list of submissions of a resource, some submissions are showing two or three times, randomly after every refresh and yes, is the same ID.

I checked MongoDB for duplicates, but there's only one.

I tried to replicate it, and it appears to happen when creating a submission in WIZARD mode, with a MULTIPLE SELECT with SAVE AS REFERENCE checked. I don't know if its mandatory, but otherwise doesn't seems to happen.

Thanks!

**Comment by wag110894** [comment]
Hello,

Thanks for reaching out to us regarding this issue. We have added this item to our backlog. For reference, the ticket number is FOR-2078. We will notify you on level of priority after our Planning meeting on Monday.

Have a great day.

Thanks,
William Gay

**Comment by MarcoFleres** [comment]
I can confirm this happens when you place a Select saved as reference inside a container (EditGrid or DataGrid), while listing the form submissions.

The problem seems to lie in the $unwind step: if the select is nested, the unwinded lookup overwrites the container's array. 

Lets stay we have the resource:
```json
{
    "type": "resource",
    "components": [
        {
            "type": "editgrid",
            "components": [
                {
                    "type": "select",
                    "reference": true,
                }
            ]
        }
    ]
}
```
With then current pipeline:

```
[
         {
          $lookup: {
            from: 'submissions',
            localField: `data.${path}._id`,
            foreignField: '_id',
            as: `data.${path}`
          }
        },
        {
            $unwind: {
              path: `$data.${path}`,
              preserveNullAndEmptyArrays: true
            }
          }
]
```
A single submission with two rows in the editGrid, will result in:

```
{
    data : {
        editGrid : {
            select : { ... }
        }
    }
},
{
    data : {
        editGrid : {
            select : { ... }
        }
    }
}
```
...when the intended result was:

```
{
    data : {
        editGrid : [
            { select : { ... } },
            { select : { ... } }
        ]
    }
}
```

I have been messing with the reference handler. The intended result can be achieved by storing the lookup in a temporal field, and merging it into the original container fields, row by row.

```
// Lookup into temporal field
{
	$lookup : {
		"from": "submissions",
		"localField": `data.${path}._id`,
		"foreignField": "_id",
		"as": "matchedReferences"
	}
},
// Reformat the field, so that it can be zipped into the container rows. In the example, componentName="select"
{
	$addFields : {
		matchedReferences : {
			$map : {
				input : "$matchedReferences",
				in : { [componentName] : "$$this" }
			}
		}
	}
},
// Zip the lookup result into the container, and merge the objects of each row. containerPath="data.editGrid"
{
	$addFields : {
		[`data.${containerPath}`] : {
			$map : {
				input : {
					$zip : {
						inputs : [ `$data.${containerPath}`, "$matchedReferences" ],
						useLongestLength : true
					}
				},
				in : { $mergeObjects : [ { $arrayElemAt : ["$$this", 0] }, {$arrayElemAt : ["$$this", 1]} ] }
			}
		},
		matchedReferences: "$$REMOVE"
	}
}
```
This works even with deeply nested selects, and with some tinkering, with multi-valued selects. The only problem is that this should only be done on nested selects, and I have not found a way of detecting the nesting, other that parsing the component path.

@wag110894 I wonder if this is the right path. It occurs to me that a correct fix should handle the container at some handler, and the reference should be oblivious of being in a container. But I have not meddled enough with pipelines and containers to suggest a fix of that nature.

**Comment by wag110894** [comment]
Hello,

Thank you for your patience while we discussed this issue. After discussion, we do not view this as a high priority on our end. If you need this fix, we do offer a chance to expedite this fix.

Please let me know if you are interested in expediting this issue and we would be happy to send you a formal quote.

Thanks,
William Gay 
Form.io Support

**Comment by ZenMasterJacob20011** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
