### ISSUE TITLE
how to add new themes to formio

### ISSUE THREAD

**Issue by srinvasneelamraju** [formio/formio#788]
Hello Formio Team,
I am having local setup of formio in angular application and i want to change the theme of formio. Is there any way to add new themes to formio

**Comment by randallknutson** [comment]
Since our forms render directly to HTML within your application, you have full CSS control over the forms. The 3.x branch of the renderer renders to bootstrap so you can use any compatible bootstrap theme or write your own. The 4.x branch has configurable html templates that can use bootstrap 3, bootstrap 4 or semantic UI for rendering. You can also create your own templates in 4.x

**Comment by AnirudhaGohokar** [comment]
Hi @randallknutson , is there any documentation or sample code available for creating own templates in 4.x?

**Comment by randallknutson** [comment]
Currently the source code is the documentation. You can see the code at https://github.com/formio/formio.js/tree/4.x/src/templates

You can override templates with:
```
import {Templates} from 'formiojs';

Templates.framework = 'semantic'; // or whatever framework you want to use.

// Then you can override specific templates with:
Templates.current = {
  input: {
    form: `<input> </input`
  }
}
```
You can also override per component or componen type based on the naming convention here: https://github.com/formio/formio.js/blob/4.x/src/components/_classes/component/Component.js#L639-L644

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
