### ISSUE TITLE
[BUG] Save as reference is not working

### ISSUE THREAD

**Issue by rchgonzaga** [formio/formio#803]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.3
- Frontend framework: 4.0.0-rc.3
- Browser: Google Chrome
- Browser version: 75.0.3770.100

## Steps to Reproduce
1. Insert a component (resource) into your form
2. Mark it as "Save as reference"

## Expected behavior
Save the submission as: ObjectId("5d134af70821340017aef43b") in the data base.

## Observed behavior
As soon as you check the "save as reference" box, the list of a form stop loading and i have to uncheck the box to see the list again.

## Example

For code or form JSON, please enclose in a code block:

**Comment by randallknutson** [comment]
Sounds like a bug in 4.x We'll add it to the backlog.

**Comment by willemderu** [comment]
I experience this bug as well. I am using the form.io Portal.  I am not sure which formio version typically runs in the formio Portal. Would it be the master branch?  Thanks for having this functionality because it is very important in any database application.   Thanks for looking into this bug, it is much appreciated.

**Comment by randallknutson** [comment]
I believe this bug should be fixed in the latest 4.x release (rc.12). This should resolve the original issue.

The formio portal is running ngFormio 2.x which is a much older version. It should be stable though with save as reference. We are working to get 4.x onto production portal as soon as we can to make sure it all works the same.
