### ISSUE TITLE
Webhook POST not working with form having file component

### ISSUE THREAD

**Issue by A-Pradeep** [formio/formio#821]
Hi , i have a form with the file component (storage Base64), whenever a submission happens in the form `without uploading the image `  . the webhook will `post` the data to the given URL . 

***for the following test ,i'm using the `request catcher`  & `webhook.site` for receive the data. 

But when  a when  a form is submitted with the uploaded image , i'm not receiving any webhook data. 
I've tried changing in the settings of `webhook action` , but still none solved it.

I've tried images from all size and i have noticed , the webhook works fine with the image size less than a 100KB  ( approx 120KB also works  fine sometime ) . 

So , will this  work if image is more than 5MB  or any limit in KB ? 

Any ways to fix this .

**Comment by jhen1422** [comment]
@A-Pradeep 
Thank you for the report.
We have added this item to our backlog and will discuss this in our weekly planning meeting next week. If you would like to expedite this issue, please email support@form.io for cost information.

Thank you!

**Comment by randallknutson** [comment]
Hi A-Pradeep,

We discussed this in our meeting and thing that there is an issue with the size of the request. When using base64 storage the file is embedded in the submission data itself which causes the request to be much larger. Our system limits this to 16MB by default for both the server and the database. However, if you have a service that is accepting the webhook it probably has a limit as well that is causing a rejection. If you are using bodyParser it defaults to 100k of body data so it may be that issue. In addition, body parser fails silently which can make this mask itself. 

There are two options on how to fix this:
1. Use a different file storage provider that does not store the file data in the submission.
2. Extend out your webhook receiver so that it allows larger data.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
