### ISSUE TITLE
Difference between DB_SECRET and "Encrypted fields secret"

### ISSUE THREAD

**Issue by mrcportillo** [formio/formio#828]
Hi, I've an on-premise server connected with the formio-portal, I wanna ask you if the "Encrypted fields secret" configuration field which is in the security section of the portal has the same effect than the "DB_SECRET" environment variable that could be passed to the server, in that case, which is the order of precedence?

formio-server image version: formio-enterprise:6.3.2

**Comment by travist** [comment]
Yes they do the same. DB_SECRET is used as the "salt" to encrypt both the Project settings as well as any other "field" encryptions. This is two-way encryption since it also is used to decrypt those settings when the API calls are made to fetch the data. It is primarily used as an encryption at rest mechanism and ensures that the only way that data is retrieved is through the API.

**Comment by mrcportillo** [comment]
Thanks for your answer @travist, do you know what happens if both are set? Which of them as the priority?

**Comment by travist** [comment]
The Encrypted Fields setting uses the DB_SECRET as the salt so not sure what you mean "if both are set". If they are both set ,then Encrypted Fields will work. You should always have DB_SECRET set, so not sure it is a valid use case when they are not both set.
