### ISSUE TITLE
Local Install Vulnerabilities

### ISSUE THREAD

**Issue by supsup** [formio/formio#889]
found 5 vulnerabilities (1 low, 2 high, 2 critical)

-- any plans to upgrade these packages to resolve criticals/high?

**Comment by randallknutson** [comment]
We just did an update yesterday with updated dependencies. Did that resolve the dependencies for you? Usually the ones that stick around are dev dependency versions that won't affect a running system so they are less critical.

**Comment by scan5415** [comment]
This issue is not solved.
I tried to install the current version with the following error:
formio-master$ npm install
npm WARN acorn-jsx@5.3.1 requires a peer of acorn@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 805 packages in 4.255s

86 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (3 low, 1 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Could you please check the dependencies?
