### ISSUE TITLE
How do you download dropbox files via the api?

### ISSUE THREAD

**Issue by Eltyo** [formio/formio#958]
## Environment
- Hosting type
  - [x] Form.io

Is calling
`https://{formioApiUrl}/form/{formId}/storage/dropbox?path_lower={path_lower}&x-jwt-token={x-jwt-token}`
the correct way to download dropbox files via api? Is there a way to use x-token api keys instead?

**Comment by randallknutson** [comment]
I took a look at the code and it appears that you can use the x-token to get the dropbox file. However, you need to pass it as a header and not as a query parameter. This also can't be done in the browser since the server will reject CORS requests using x-token for security reasons. You can do this for server to server communication.

**Comment by Eltyo** [comment]
Thanks mate :)
