### ISSUE TITLE
[BUG] PATCH-ing a user removes their password

### ISSUE THREAD

**Issue by mikeyjkmo** [formio/formio#984]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 1.75
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Create a user
2. Patch the user, replacing their email:

```
PATCH /user/<id>/submission with:

[
  {
  	"op": "replace",
  	"path": "/data/email",
  	"value": "newemail@example.com"
  }
]
```

3. Try to log in as the user

## Expected behavior
Password should be retained after a patch that doesn't involve it.

## Observed behavior
User can no longer log in after their email has been patched.

**Comment by wag110894** [comment]
Thank you for reaching out!

We have created a ticket and have added this to our backlog. For Reference, the ticket number is FOR-2667. We welcome a pull request and have a process to expedite if you are interested. If you are interested in expediting, then please contact support@form.io.

**Comment by wag110894** [comment]
@mikeyjkmo We did discuss this issue that you are experiencing and it was not considered a high priority for our platform, so it may be several months before it is released. If this is urgent for you we do offer expedited development for half of our normal rate to move this up as a higher priority.  Please contact support@form.io if you are interested in expediting or interested in how many hours it will take to resolve this issue. Please reference FOR-2667 in your email when contacting support.

**Comment by blochealth** [comment]
@wag110894  I am attempting to use Form.io's PATCH as instructed here: https://documenter.getpostman.com/view/684631/formio-api/2Jvuks?version=latest and the problems with it are MUCH larger than just this reported bug. 
Here is a SMALL sampling of problems with Form.io's Patch implementation

Does nothing, but does not return an error:
```
[
  {
  	"op": "add",
  	"path": "/custom_metadata",
  	"value": 2
  }
]
```

Removes the 'password' property from the User resource (as noted above): 
```
[
  {
  	"op": "add",
  	"path": "/data/fullName",
  	"value": "Fixer 16"
  }
]
```

Does nothing but does not report an error: 
```
[
  {
  	"op": "add",
  	"path": "/data/custom_property",
  	"value": "Not on form"
  }
]
```

Does nothing but does not report an error: 
```
[
  {
  	"op": "remove",
  	"path": "/roles"
  }
]
```
I am adding this comment here to save @mikeyjkmo and any other developers (including premium paid subscribers) time and stating that the PATCH API listed in the postman documentation above basically DOES NOT WORK as in the example in the latest release of Form.io as of 5/11/2020. You have to rely on POST instead and manage the state yourself client side, which is terrible but the only workaround.

**Comment by mikeyjkmo** [comment]
@blochealth Hi, as far as I'm aware I you can only set fields under the "data" path. So custom metadata isn't supported outside of "data"...

**Comment by travist** [comment]
@blochealth it seems that the only one that is wrong here is the Password item. The other items work as designed because our API platform silently strips away any superfluous information, which is also what happens during POST and PUT so your comments regarding that PATCH does not work is not correct.  Example...

You said...

```
[
  {
  	"op": "add",
  	"path": "/custom_metadata",
  	"value": 2
  }
]
```
Does not work and does not return an error:  Correct because this is not accepted data and is ignored. No error is thrown as you would expect also with PUT and POST.

You said...

```
[
  {
  	"op": "add",
  	"path": "/data/custom_property",
  	"value": "Not on form"
  }
]
```
Does nothing but does not report an error:  Correct because there is not a field on the form with this property. The validator silently strips away superfluous information and also is expected from both PUT and POST.

You said...
```
[
  {
  	"op": "remove",
  	"path": "/roles"
  }
]
```

Does nothing but does not report an error:  Correct because our API platform protects roles and does not allow modifications to them via API. Otherwise it could be a security issue. This is expected and you would see the same result from POST and PUT.

So, as far as I can tell, there is only ONE problem. The issue with the password and we are aware of that and it is getting resolved. The other items are expected and also work the same way with POST and PUT so for you to complain that PATCH is broken because of that is not well placed and is just mudding the waters.

**Comment by blochealth** [comment]
@travist, this is a problem because your tech support told me back in October that "PUT" supported direct role modification when permissions on the submission were adequate.  That's why I thought it should work and reported the issue.  

If the API doesn't support this then there is no way at all to remove group permissions once they have been added: the Form.io Premium Actions only supports a "group assignment" action with no mirrored "removal" action. The below message was given to me as a workaround"

> Hi Adrienne,
​
Great to hear from you.
Allow me to clarify.
You can simply perform a PUT request on the submission object and remove the "roles" provided by that group. Group assignment simply takes the ID of the group and adds that to the "roles" array of the submission object. You can remove roles using PUT requests, but cannot add or modify roles.

Hope this helps.
Please let me know if you have any further questions.
Thanks,
William Gay

**Comment by travist** [comment]
You should only be able to remove roles, but not add them using PUT. It is possible that this doesn't work with PATCH but that would be considered edge case and not deemed critical enough to get prioritized.

**Comment by blochealth** [comment]
@travist, after some digging I've discovered a bug with PUT that was causing my symptoms as well. Filed as #994, but has a workaround.  Likely not specific to patch.

**Comment by travist** [comment]
That makes sense. I will re-add that bug to our development backlog so that it gets looked at. I agree it needs to be resolved.

**Comment by cmcortez** [comment]
@blochealth We will transfer this issue over to our regular support system. Thank you.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
