### ISSUE TITLE
[Question] Using Step size with Time Component

### ISSUE THREAD

**Issue by CyborgChimp88** [formio/formio#991]
Hi,

There is a Date/Time component where you can configure the Step sizes for hour and minutes. 
Though these options don't exist with the Time Component. 
Is there a way to configure the step increment of the minutes with the calculated value or with any other fields?

Thanks

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
