### ISSUE TITLE
BUG: PUT request to remove roles does not work unless you ALSO attempt to add a role. 

### ISSUE THREAD

**Issue by blochealth** [formio/formio#994]
https://github.com/formio/formio/blob/fb93f3e1c62cebfc3f4409607a624815f4bb31b7/src/middleware/submissionHandler.js#L121

This feature: https://github.com/formio/formio/commit/2abf5b28f13dcf588601fb02b8903e9368e4d8ca. 

was intended to allow only the removal of roles via the PUT request on a Form.io submission. 

There is a test in it that uses the following PASSING test case: 

Manager with 2 'roles', A and B.  PUT request tries to replace this with roles 'A and C'. The correct behavior happens: the Manager is left with only role 'A' after the update. I can reproduce this behavior with my current setup (form.io enterprise hosted in docker, running Application: 7.0.3, Renderer: 4.9.22) 

However, a simpler test case doesn't work: 
Manager with 2 'roles', A and B.  PUT request tries to replace this with role 'A'.  The Manager still has roles  'A' and 'B' after the update (with Response 200 from the request). I can reproduce this behavior with my current setup (form.io enterprise hosted in docker, running Application: 7.0.3, Renderer: 4.9.22) 

So my workaround for now is to add a fake role along with the ones I'm trying to keep (Manager with role A and B, PUT request with A and NOTREAL, results in role A being the one left).

**Comment by travist** [comment]
We will take a look.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
